name: Deploy to zoghby.net

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build PDF with nix
        run: nix build ./resume

      - name: Prepare Public Directory
        # Nix outputs symlinks. We copy the actual file to a deployment folder.
        # Change 'result/my-document.pdf' to your actual compiled file path inside the nix result.
        run: |
          cp -L result/andrew_zoghby_resume.pdf public/
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Instructs GitHub to only deploy the contents of the newly made folder
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

